### ISSUE TITLE
Add ability to specify log dir

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-provider-verifier#10]
Logs are output to `./log/pact.log`, it would be nice to be able to specify where logs are output.

**Comment by bethesque** [comment]
Will need to add this option to the underlying CLI.

**Comment by vaidik** [comment]
I would like to have this ability too. Makes it difficult to work with mounted volumes in Docker

**Comment by bethesque** [comment]
This is already implemented. Sorry I didn't remember to close the issue.

```
  -o, [--out=FILE]
        # Write output to a file instead of $stdout.
```
