### ISSUE TITLE
option to provide pact-broker address is missing

### ISSUE THREAD

**Issue by dhoomakethu** [pact-foundation/pact-provider-verifier#11]
pact-provider-verifier provides option to specify broker username and broker passwork but does not provide an option to specifiy the broker host url. Trying to publish the results to pact-broker fails .

`bundle exec rake pact:verify:at[riptide_broker:*****@/tmp/pacts/1-2.json] PACT_DESCRIPTION="a request is made to validate user" PACT_PROVIDER_STATE="" # A request is made to validate user

For assistance debugging failures, run `bundle exec rake pact:verify:help`

/usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/create.rb:31:in `count_failures_for_pact_json': undefined method `collect' for nil:NilClass (NoMethodError)
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/create.rb:35:in `any_failures?'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/create.rb:17:in `call'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/create.rb:8:in `call'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/publish_all.rb:28:in `block in verification_results'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/publish_all.rb:27:in `collect'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/publish_all.rb:27:in `verification_results'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/publish_all.rb:19:in `call'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/verification_results/publish_all.rb:10:in `call'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/pact_spec_runner.rb:86:in `block (2 levels) in configure_rspec'
	from /usr/local/bundle/gems/pact-support-0.6.1/lib/pact/rspec.rb:43:in `with_rspec_3'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/pact_spec_runner.rb:85:in `block in configure_rspec'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/example.rb:378:in `instance_exec'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/hooks.rb:364:in `run'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `block in run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `each'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1660:in `run_hooks_with'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1629:in `with_suite_hooks'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:114:in `block in run_specs'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/reporter.rb:77:in `report'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:113:in `run_specs'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:89:in `run'
	from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/pact_spec_runner.rb:94:in `run_specs'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/provider/pact_spec_runner.rb:35:in `run'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/cli/run_pact_verification.rb:22:in `call'
	from /usr/local/bundle/gems/pact-1.11.1/lib/pact/cli/run_pact_verification.rb:14:in `call'
	from /usr/local/bundle/gems/pact-provider-verifier-1.0.1/lib/pact/provider_verifier/app.rb:75:in `block in verify_pacts'
	from /usr/local/bundle/gems/pact-provider-verifier-1.0.1/lib/pact/provider_verifier/app.rb:64:in `collect'
	from /usr/local/bundle/gems/pact-provider-verifier-1.0.1/lib/pact/provider_verifier/app.rb:64:in `verify_pacts'
	from /usr/local/bundle/gems/pact-provider-verifier-1.0.1/lib/pact/provider_verifier/cli.rb:21:in `verify'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/bundle/gems/pact-provider-verifier-1.0.1/bin/pact-provider-verifier:3:in `<top (required)>'
	from /usr/local/bundle/bin/pact-provider-verifier:22:in `load'
	from /usr/local/bundle/bin/pact-provider-verifier:22:in `<main>'`

**Comment by mefellows** [comment]
Hmm what's the use case here? Publishing Verification results?

Currently, the Verifier does not automatically retrieve Pacts from a Pact Broker - it needs to be given the URLs (via `--pact-urls`). If you provide credentials, it will use them as basic auth to authenticate to the each of the URL provided - that may or may not be a Broker.

If those URLs happen to be a Pact Broker, and the pact contents contain the correct HAL links, this should work. Looking at your example they are local pacts so this is unlikely to work - the Gem won't know either a) the host to publish to or b) the link to follow and create the results.

cc: @bethesque

**Comment by bethesque** [comment]
It shouldn't blow up though! Let me have a look though.

**Comment by bethesque** [comment]
I think it's something to do with the version of rspec. What version of rspec are you using?

**Comment by bethesque** [comment]
I can get it to blow up with 3.0.4, but it works with the latest rspec. @dhoomakethu can you run "gem install rspec" and make sure it gives you 3.6.0.

I'll see what I can do about making the code backwards compatible.

**Comment by dhoomakethu** [comment]
I am running it on docker container [pact-provider-verifier-docker](https://github.com/DiUS/pact-provider-verifier-docker). Any how as @mefellows suggested I will try with pact-broker urls and see if that helps.

**Comment by bethesque** [comment]
We'll need a new release of the docker container then. Let me look into it. As matt says, only pacts that can came from a broker can have results published back to a broker.

**Comment by bethesque** [comment]
@dhoomakethu using pact-broker urls will not help, it's an issue to do with an old version of rspec.

**Comment by dhoomakethu** [comment]
Ok , I tried with the pact url from a broker running locally (again docker container from [pact-broker](https://hub.docker.com/r/dius/pact_broker/)) , The tests ran as usual but failed to upload the verification results with this warning.

`WARNING: Cannot publish verification for auth as there is no link named pb:publish-verification-results in the pact JSON. If you are using a pact broker, please upgrade to version 2.0.0 or later.`

I am currently using pact-python to generate the pact json files and running the provider verification manually. Not sure what json field needs to be updated in the pact file to publish verification result to the broker.

**Comment by bethesque** [comment]
The docker broker you have is now deprecated. Can you use this one please? https://hub.docker.com/r/dius/pact-broker/

**Comment by dhoomakethu** [comment]
Tried both latest and 2.0.0-beta tagged containers, same warning is still observed.

**Comment by bethesque** [comment]
I've just done a new build and tested it locally, and it's working correctly. Can you check a few things for me? In the response from the broker, you should have the following header `X-Pact-Broker-Version: 2.0.2`. In the pact json, you should also have a link that looks like this:

```json
{
  "_links": {
    "pb:publish-verification-results": {
      "href": "http://192.168.99.100/pacts/provider/Bar/consumer/Foo/pact-version/60053ab12c11a1e2d4f7543aefce14af14f46d7c/verification-results",
      "title": "Publish verification results"
    }
}
```

**Comment by dhoomakethu** [comment]
The response does have the field b:pub;lish-verification-results(response attached below),  though I do not see the header you have mentioned
`
{
    "consumer": {
        "name": "auth"
    },
    "provider": {
        "name": "userservice"
    },
    "interactions": [
        {
            "description": "a request is made to validate user with invalid password",
            "request": {
                "method": "get",
                "path": "/validate",
                "query": "password=blablabla&userid=tada@bla.com"
            },
            "response": {
                "status": 400,
                "headers": {}
            }
        },
        {
            "description": "a request is made to validate user with non existing user",
            "request": {
                "method": "get",
                "path": "/validate",
                "query": "password=blablabla%21&userid=nonexisting%40riptideio.com"
            },
            "response": {
                "status": 404,
                "headers": {}
            }
        },
        {
            "description": "a request is made to validate user",
            "request": {
                "method": "get",
                "path": "/validate",
                "query": "password=blablabla%21&userid=tada@bla.com"
            },
            "response": {
                "status": 200,
                "headers": {},
                "body": "{\"userid\":\"admin@riptideio.com\",\"roles\":[\"admin\",\"superuser\"],\"full_name\":\"Riptide Administrator\",\"email\":\"admin@riptideio.com\",\"client_ids\":[\"riptideio\"],\"is_active\":true,\"created_on\":\"2017-05-18T06:52:39.34Z\"}"
            }
        }
    ],
    "PublishVerificationResults": true,
    "ProviderVersion": "0.0.20",
    "metadata": {
        "pactSpecification": {
            "version": "2.0.0"
        }
    },
    "createdAt": "2017-05-23T05:08:56+00:00",
    "_links": {
        "self": {
            "title": "Pact",
            "name": "Pact between auth (v0.0.5) and userservice",
            "href": "http://*.*.*.*:9080/pacts/provider/userservice/consumer/auth/version/0.0.5"
        },
        "pb:consumer": {
            "title": "Consumer",
            "name": "auth",
            "href": "http://*.*.*.*:9080/pacticipants/auth"
        },
        "pb:provider": {
            "title": "Provider",
            "name": "userservice",
            "href": "http://*.*.*.*:9080/pacticipants/userservice"
        },
        "pb:latest-pact-version": {
            "title": "Pact",
            "name": "Latest version of this pact",
            "href": "http://*.*.*.*:9080/pacts/provider/userservice/consumer/auth/latest"
        },
        "pb:previous-distinct": {
            "title": "Pact",
            "name": "Previous distinct version of this pact",
            "href": "http://*.*.*.*:9080/pacts/provider/userservice/consumer/auth/version/0.0.5/previous-distinct"
        },
        "pb:diff-previous-distinct": {
            "title": "Diff",
            "name": "Diff with previous distinct version of this pact",
            "href": "http://*.*.*.*:9080/pacts/provider/userservice/consumer/auth/version/0.0.5/diff/previous-distinct"
        },
        "pb:pact-webhooks": {
            "title": "Webhooks for the pact between auth and userservice",
            "href": "http://*.*.*.*:9080/webhooks/provider/userservice/consumer/auth"
        },
        "pb:tag-prod-version": {
            "title": "Tag this version as 'production'",
            "href": "http://*.*.*.*:9080/pacticipants/auth/versions/0.0.5/tags/prod"
        },
        "pb:tag-version": {
            "title": "Tag version",
            "href": "http://*.*.*.*:9080/pacticipants/auth/versions/0.0.5/tags/{tag}"
        },
        "pb:publish-verification-result": {
            "title": "Publish verification",
            "href": "http://*.*.*.*:9080/pacts/provider/userservice/consumer/auth/pact-version/b781e9dba61454d28fb54a3f0473ff22fd1c7ead/verification-results"
        },
        "curies": [
            {
                "name": "pb",
                "href": "http://*.*.*.*:9080/doc/{rel}",
                "templated": true
            }
        ]
    }
}
`

**Comment by bethesque** [comment]
It's singular, "publish-verification-result" instead of plural "publish-verification-results". That makes me think you've still got an old version of the docker image somehow. I think the singular was only ever in a beta release.

**Comment by dhoomakethu** [comment]
Ok, I pulled the latest again 
`dius/pact-broker                     latest                 38ec76403bf0        4 hours ago         785MB`
The problem with this version is I am not able publish pacts to the broker. I get 403 forbidden for my PUT requests with a warning the log
`WARN -- : attack prevented by Rack::Protection::HttpOrigin`

Note I am running the pact broker on google cloud and pacts are being pushed from my localhost

**Comment by bethesque** [comment]
The latest version uses Rack::Protection to avoid typical attacks. Something in this code is triggering a denial.

```ruby
require 'rack/protection'

module Rack
  module Protection
    ##
    # Prevented attack::   CSRF
    # Supported browsers:: Google Chrome 2, Safari 4 and later
    # More infos::         http://en.wikipedia.org/wiki/Cross-site_request_forgery
    #                      http://tools.ietf.org/html/draft-abarth-origin
    #
    # Does not accept unsafe HTTP requests when value of Origin HTTP request header
    # does not match default or whitelisted URIs.
    class HttpOrigin < Base
      DEFAULT_PORTS = { 'http' => 80, 'https' => 443, 'coffee' => 80 }
      default_reaction :deny

      def base_url(env)
        request = Rack::Request.new(env)
        port = ":#{request.port}" unless request.port == DEFAULT_PORTS[request.scheme]
        "#{request.scheme}://#{request.host}#{port}"
      end

      def accepts?(env)
        return true if safe? env
        return true unless origin = env['HTTP_ORIGIN']
        return true if base_url(env) == origin
        Array(options[:origin_whitelist]).include? origin
      end

    end
  end
end
```

**Comment by bethesque** [comment]
What tool are you using to publish the pacts?

**Comment by dhoomakethu** [comment]
I am using POSTMAN to publish pact . I was able to publish from with in the HAL browser and provider verification tests did publish the results to the broker . I know this if going off topic but is there a way to bypass the Rack::Protection module and publish the pacts ?

**Comment by bethesque** [comment]
We went off topic ages ago! This was never about the title of the issue ;)

Ah, that makes sense that you're using postman. It had to be from within a browser, otherwise you wouldn't be getting CORS issues. I'm just doing some debugging on my local machine, and I'm surprised to find that postman is setting the Origin header to "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop". This is what is causing the problem.

Having a bit of a read tells me that checking the Origin header is quite a weak protection any way, so I will see how to disable it or take it out.

**Comment by bethesque** [comment]
Ok, if you want a quick and dirty fix, here's how to get rid of the origin check.

```
docker exec -it CONTAINER_NAME bash
vim /home/app/pact_broker/vendor/bundle/ruby/2.2.0/gems/pact_broker-2.0.2/lib/pact_broker/app.rb
# go to line 60
# Add :http_origin the array of protections to ignore. eg.
# @app.use Rack::Protection, except: [:remote_token, :session_hijacking, :http_origin]]
passenger-config restart-app --name /home/app/pact_broker/public
```
I'll work out what to do about a longer term solution in the morning.

**Comment by dhoomakethu** [comment]
cool, thanks for the hint !
