### ISSUE TITLE
[enhancement] add ability to output to a file

### ISSUE THREAD

**Issue by ewortzman** [pact-foundation/pact-provider-verifier#21]
The `pact-provider-verifier` currently has format options to output as JSON or as JUnit.  But the output is still written to the console.  In order to get an actual json or junit file, the output has to be piped to a files using `>>` or `&>` or something. There are a few issues with this:

1. since all contracts go to the same output stream, all contract verifications will be output to the same stream (unless some pass and some fail, see below).  This means that it requires additional processing to get each verification result to its own file.
2. if a contract passes, it is output to `STDOUT`, but if it fails, it is output to `STDERR`.  Because these are separate streams, the output will not always appear in the order the contracts were run. This means more extra processing to determine where each verification output ends and the next begins, and which output refers to which contract. (It's possible that the output may actually be non-deterministic. I'm actually not sure. If so, that's an even bigger problem)
3. There are additional lines of output that get printed to stdout or stderr. For example, "INFO: Reading pact at ..." and "WARN: Ignoring unsupported matching rules ...".  These lines would have to be stripped out of the results in order to get valid output, which requires even more additional processing.

It would be useful to have the ability to output verification results directly to a file, on a contract-by-contract basis.  For example, if I call a broker to get contracts for `provider`, which has contracts with `consumer1`, `consumer2`, and `consumer3`, and I choose `RspecJunitFormatter` output, I would like to specify an optional `--output-dir` parameter, which would be populated with 3 files: `provider-consumer1-results.xml`, `provider-consumer2-results.xml`, and `provider-consumer3-results.xml`.

**Comment by bethesque** [comment]
Yes, good suggestion.

**Comment by bethesque** [comment]
One thing that slightly complicates the naming of the output files is that you may verify multiple pact versions for the same consumer/provider pair. eg `.../latest/master`, `../latest/prod`. We could add the consumer version number in there, however, this would only be possible if the pact was retrieved from a pact broker.

We could clear out the directory each time, and arbitrarily number the files if there is a duplicate consumer/provider pair, but I always get nervous having tools that go "delete everything from this directory" in case they accidentally point it at /usr/home or something stupid!

**Comment by ewortzman** [comment]
I can think of 2 options, but I think there is definitely an issue with how to handle local files vs broker contracts:

1. use a path like `${output_dir}/provider/consumer/${version}_results.xml` or something. Makes it easy to find the contracts after they're run.  But the downside is that local files don't have a version attached
2. for local files, just use `${output_dir}/${relative_path_to_contract_file}_results.xml`.  Similarly easy to find, but has the problem that broker contracts don't have a relative path.

**Comment by ewortzman** [comment]
To add to this request, it would also be useful to have the ablity to output in multiple formats.  For example, it would be nice to be able to output to STDOUT in Pact's pretty, human-readable format, while also generating a machine parseable junit file that goes to `--output-dir`

**Comment by bethesque** [comment]
Agreed. Sorry, I can't pick this up right now, as I have a heap of urgent things to look at, but if you'd like to have a go, I'm happy to accept PRs. Changing the output is reasonably straightforward, however, accepting multiple arguments for the streams requires a small hack to Thor that I'd need to copy in from another project.

**Comment by bethesque** [comment]
I've added a `--out FILE` option to the command in the latest version. It doesn't split the results up per contract yet, but I thought I'd let you know @ewortzman in case it was useful for you anyway as it is.

**Comment by YOU54F** [comment]
closing due to lack of response, and the feature being implemented as per https://github.com/pact-foundation/pact-provider-verifier/issues/21#issuecomment-381449268 and documented in the readme

if someone wants the feature on a contract by contract basis, please feel free to raise
