### ISSUE TITLE
Add ability to ignore certificate errors on pact urls

### ISSUE THREAD

**Issue by Deseao** [pact-foundation/pact-provider-verifier#23]
For various reasons my Pact Broker is running over https with a self signed certificate. When I attempt to use this gem, I get an x509: certificate signed by unknown authority error. I would like to be able to call the pact-provider-verifier with a --insecure argument to allow skipping TLS/SSL verification.

**Comment by bethesque** [comment]
You should be able to give the verifier a certificate using the SSL_CER_FILE or SSL_CERT_DIR env vars.

**Comment by Deseao** [comment]
Good to know, thank you very much.
