### ISSUE TITLE
array "min" is implemented as "equals"

### ISSUE THREAD

**Issue by souliane** [pact-foundation/pact-provider-verifier#24]
Hi,
the array "min" rule implementation seems to be wrong, it is a priori doing as "equals" would do.

If my pact defines "min: 3" and the provider returns 3 elements, it works.
If the provider returns 2 elements, it fails as expected.
But if there are 4 elements, it also fails with something like:

`Actual array is too long and should not contain a Hash at $[0].site_address.value.country.meta_info.choices[3]
`

Thanks.

**Comment by bethesque** [comment]
I can't recreate this. 

Here is the commit: 
https://github.com/pact-foundation/pact-ruby-e2e-example/commit/13090e805507ff4505aecf1691f10561aff3e874 

Here is the travis build: https://travis-ci.org/pact-foundation/pact-ruby-e2e-example/builds/400230297

You'll notice that there is an array `Pact.each_like({ location: "Sydney", capacity: 5 }, { min: 3 })` and that the provider returns 4 items. When I change the array to have 2 items, it fails.

(Ignore the `WARN: Ignoring unsupported matching rules {"min"=>3} for path $['body']['factories']` in the logs. I really have to fix that.)

Can you please provide an executable example demonstrating the issue?

**Comment by souliane** [comment]
Hi,

I can't reproduce the issue myself, even when I restore the working environment where it happened... maybe I got confused.

Thanks and sorry for wasting your time! :-/

**Comment by totycro** [comment]
Hi,

I'm working with @souliane on the same project.

Thanks @bethesque for the example branch. I think i managed to get it to fail by nesting the `each_like` inside a `like`:

https://github.com/totycro/pact-ruby-e2e-example/commit/a99b17142252b39d5553b4b3142e6965a977e506

Now the pact only verifies if there are exactly 3 Sydneys and fails with 4, even though `min` is still set to 3.

Could you look into that?

**Comment by bethesque** [comment]
This will be fixed in the next release of pact-js when @mefellows upgrades to v1.54.1 of the standalone.
