### ISSUE TITLE
Throw better error messages if invalid pact files given

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-provider-verifier#25]
It turns out if you pass a valid JSON document to the verifier, that it will return a cryptic error, which bubbles up to the wrapper language.

You can reproduce the issue like so:

```sh
echo '{"foo":"bar"}' > foo.json
pact-provider-verifier --provider-base-url foo foo.json
```

Which should produce:

```
/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.6.0/lib/pact/consumer_contract/consumer_contract.rb:44:in `from_hash': No consumer contract parser found for hash: {"foo"=>"bar"} (Pact::Error)
```

A useful error message to help people get to the bottom of the issue would be nice here.

See https://github.com/pact-foundation/pact-node/issues/98 for background.

**Comment by bethesque** [comment]
The code that throws that is trying to work out which parser to use, and it iterates though all the possible parsers, and that's what gets thrown when none of them match.

How about `This document does not use a recognised Pact format`?

**Comment by mefellows** [comment]
I think we should also reference the specific URL that is failing, to help diagnosis:

e.g. 

`This document does not use a recognised Pact format, please check that <path to file> is a valid pact file`

**Comment by mefellows** [comment]
This should also help with https://github.com/pact-foundation/pact-go/issues/50.

**Comment by bethesque** [comment]
Hm. I don't have the reference to the path at that stage - just the hash.

```
raise Pact::Error.new("This document does not use a recognised Pact format: #{hash}")
```

I'll see what I can do.

**Comment by mefellows** [comment]
Fair enough. Your first suggestion is at least a good starting point, and the verifier already logs out the file name:

e.f.
```
INFO: Reading pact at /Users/mfellows/development/public/pact-js/examples/e2e/pacts/matching_service-animal_profile_service.json
...
INFO: Reading pact at dXfltyFMgNOFZAxr8io9wJ37iUpY42M:*****@/Users/mfellows/development/public/pact-js/examples/e2e/pacts/matching_service-animal_profile_service.json
```

**Comment by bethesque** [comment]
It actually wasn't hard in the end. It'll be out in the next release.

**Comment by mefellows** [comment]
Awesome, thanks!
