### ISSUE TITLE
Allow log level to be configurable via the CLI

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-provider-verifier#26]
AS a client library (e.g. Pact JS)
I would like to be able to control log output of the verifier
SO that it is consistent with the rest of the framework output

Typically, our client interfaces have the ability to specify the log level, and it is surprising when `ERROR` or above is set and the verifier spits out `WARN`s, for example.

If we can control the output in the verifier, we can make the component less visible in the framework.

See https://github.com/pact-foundation/pact-node/issues/109#issuecomment-414638822 for 
background.

**Comment by mefellows** [comment]
Update on this issue.

I just noticed this causing an issue for Pact Go when upgrading binary ranges. When serialising the Verification response as JSON, there is an "INFO" message that is printed. So the response comes in something like this:

```
INFO: Fetching pacts for loginprovider from https://test.pact.dius.com.au/
...
{"version":"3.8.0","examples":[{"id":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb[1:1:1:1:1:1]","description":"has status code 401","full_description":"Verifying a pact between jmarie and loginprovider Given User jmarie is unauthenticated A request to login with user 'jmarie' with GET /users/10 returns a response which has status code 401","status":"passed","file_path":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb","line_number":151,"run_time":0.017269,"pending_message":null},{"id":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb[1:1:1:1:1:2:1]","description":"\"Content-Type\" which matches /application\\/json/","full_description":"Verifying a pact between jmarie and loginprovider Given User jmarie is unauthenticated A request to login with user 'jmarie' with GET /users/10 returns a response which includes headers \"Content-Type\" which matches /application\\/json/","status":"passed","file_path":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb","line_number":160,"run_time":0.000116,"pending_message":null}],"summary":{"duration":0.018702,"example_count":2,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"2 examples, 0 failures"}
```

I can guard around the non-JSON bits, bit it would be preferable to disable logging (or log to file) in these cases.

I think this commit is the culprit: https://github.com/pact-foundation/pact-ruby/commit/06fa61581512ba5570c315d089f2c0fc23c8cb11

**Comment by bethesque** [comment]
Needs to be added as an option here: https://github.com/pact-foundation/pact-provider-verifier/blob/master/lib/pact/provider_verifier/cli/verify.rb

here: https://github.com/pact-foundation/pact-provider-verifier/blob/master/lib/pact/provider_verifier/app.rb#L134

and here: https://github.com/pact-foundation/pact-ruby/blob/830d1caf098584ed23f086809c82f6e643e431d8/lib/pact/cli/run_pact_verification.rb

And the level actually set here: https://github.com/pact-foundation/pact-ruby/blob/62075209776a11184369948830c8361dd8330a6d/lib/pact/provider/pact_spec_runner.rb#L130

But now I think about it, it isn't using a proper logger with levels. It's just calling stream.puts("WARN: ...") and stream.puts("ERROR: ..."). Argh.

**Comment by alexfdz** [comment]
> Update on this issue.
> 
> I just noticed this causing an issue for Pact Go when upgrading binary ranges. When serialising the Verification response as JSON, there is an "INFO" message that is printed. So the response comes in something like this:
> 
> ```
> INFO: Fetching pacts for loginprovider from https://test.pact.dius.com.au/
> ...
> {"version":"3.8.0","examples":[{"id":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb[1:1:1:1:1:1]","description":"has status code 401","full_description":"Verifying a pact between jmarie and loginprovider Given User jmarie is unauthenticated A request to login with user 'jmarie' with GET /users/10 returns a response which has status code 401","status":"passed","file_path":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb","line_number":151,"run_time":0.017269,"pending_message":null},{"id":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb[1:1:1:1:1:2:1]","description":"\"Content-Type\" which matches /application\\/json/","full_description":"Verifying a pact between jmarie and loginprovider Given User jmarie is unauthenticated A request to login with user 'jmarie' with GET /users/10 returns a response which includes headers \"Content-Type\" which matches /application\\/json/","status":"passed","file_path":"/opt/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/rspec.rb","line_number":160,"run_time":0.000116,"pending_message":null}],"summary":{"duration":0.018702,"example_count":2,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":0},"summary_line":"2 examples, 0 failures"}
> ```
> 
> I can guard around the non-JSON bits, bit it would be preferable to disable logging (or log to file) in these cases.
> 
> I think this commit is the culprit: [pact-foundation/pact-ruby@06fa615](https://github.com/pact-foundation/pact-ruby/commit/06fa61581512ba5570c315d089f2c0fc23c8cb11)

@mefellows we are facing this issue. Are you aware of any workaround?

**Comment by bethesque** [comment]
When the output is set to json, the normal output stream gets sent to stderr instead of stdout to fix this exact problem. https://github.com/pact-foundation/pact-ruby/blob/master/lib/pact/cli/run_pact_verification.rb#L90

I can't think how this is happening.

**Comment by mefellows** [comment]
@alexfdz I don't believe this is an issue for pact-go anymore - can you please raise an issue at https://github.com/pact-foundation/pact-go/issues if it still is?

**Comment by YOU54F** [comment]
Feature has been added

https://github.com/pact-foundation/pact-provider-verifier/commit/1cf71bb625d1187b121df5f2aea93259133b8d0d
