### ISSUE TITLE
unable to verify pact from cli

### ISSUE THREAD

**Issue by arun290636** [pact-foundation/pact-provider-verifier#32]
running this on mac

below error is displayed when i run - ./pact-provider-verifier --PACT_URL=baseurl/pacts/provider/catalogApi/consumer/magento/latest -h, --provider-base-url=url

pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:49:in `read'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:49:in `get_local'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:39:in `render_pact'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:22:in `read'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_source.rb:14:in `pact_json'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:116:in `collect'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:116:in `pact_jsons'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:79:in `configure_rspec'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:151:in `verify_pact'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:33:in `block in call'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:32:in `collect'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:32:in `call'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:26:in `call'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/cli/verify.rb:37:in `verify'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
/Users/arun.kumar/Arun-personal/learning/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'
/Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:49:in `read': No such file or directory @ rb_sysopen - --PACT_URL=http://10.10.0.234:32625/pacts/provider/catalogApi/consumer/magento/latest (Errno::ENOENT)
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:49:in `get_local'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:39:in `render_pact'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.9.0/lib/pact/consumer_contract/pact_file.rb:22:in `read'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_source.rb:14:in `pact_json'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:116:in `collect'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:116:in `pact_jsons'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:79:in `configure_rspec'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/provider/pact_spec_runner.rb:33:in `run'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:21:in `call'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-1.38.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:151:in `verify_pact'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:33:in `block in call'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:32:in `collect'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:32:in `call'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/app.rb:26:in `call'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/cli/verify.rb:37:in `verify'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.22.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
	from /Users/arun.kumar/Arun-personal/learning/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'

**Comment by mefellows** [comment]
`--PACT_URL=` is not a flag, each pact you want to specify should be the first first positional arguments to the CLI.

**Comment by bethesque** [comment]
`./pact-provider-verifier http://broker/pacts/provider/catalogApi/consumer/magento/latest --provider-base-url http://provider`

**Comment by bethesque** [comment]
Btw, you can actually just give the pact-provider-verifier the base URL of the pact broker, and the name of the provider, and it will work out the rest.
