### ISSUE TITLE
'application/x-www-form-urlencoded' not replayed correctly?

### ISSUE THREAD

**Issue by tknino** [pact-foundation/pact-provider-verifier#33]
My consumer test looks like this
 ```
   (pact
     .given('everything is ideal')
     .upon_receiving('request for device and user codes')
     .with_request(
        method='POST',
        path="/",
        headers={'Content-Type': 'application/x-www-form-urlencoded'},
        body=Like({
                    "client_id": ["test1"],
                    "client_secret": ["test1-secret-key"],
                    "scope": ['openid', 'profile', 'phone', 'offline_access']
                    })
     )
     .will_respond_with(200, body=Like(expected)))
    with pact:
        consumer.get_device_n_user_codes('test1', 'test1-secret-key',
                                         'openid profile phone offline_access', imposter=pact.uri + '/')
  ```

When verifying pact I expect the request to have `client_id=test1&client_secret=***-key&scope=openid+profile+phone+offline_access` like displayed on the screenshot

![verifying1](https://user-images.githubusercontent.com/18438020/56036412-7b9c4700-5d35-11e9-9a82-bbb10d6dbe06.PNG)

Instead, I'm getting this `{"client_id":["test1"],"client_secret":["test1-secret-key"],"scope":["openid","profile","phone","offline_access"]}`

![verifying2](https://user-images.githubusercontent.com/18438020/56036572-dafa5700-5d35-11e9-8272-bdc4aacc67a7.PNG)

**Comment by bethesque** [comment]
Can you please follow the instructions for reproducing the issue using this codebase please? https://github.com/pact-foundation/pact-ruby-e2e-example

**Comment by tknino** [comment]
My code is in Python. I'm just using [Pact Provider Verifier](https://github.com/pact-foundation/pact-provider-verifier) as it is cross-platform tool (and I had some issues to get the pactman-verifier going)

**Comment by bethesque** [comment]
The underlying code of the provider verifier is ruby. It would save me time and help me get the bug fixed if you can reproduce it for me. If you can python, you can ruby ;) The instructions are quite straightforward.

**Comment by bethesque** [comment]
This one might be easier though - you don't have to ruby https://github.com/pact-foundation/pact-ruby-standalone-e2e-example
