### ISSUE TITLE
Json :: Parser Error When end-point returning simple string

### ISSUE THREAD

**Issue by tanmoy1990** [pact-foundation/pact-provider-verifier#35]
Try to make V2 Contract Test For A Simple End-point. The End-Point is returning Simple String. Consumer Pact is working as expected but provider is failed to validated that. Please help me to resolve this 
 Mock Provider Service ::
`_mockProviderService
                          .Given("Get user with id '1'")
                          .UponReceiving("A GET request to retrieve the user")
                          .With(new ProviderServiceRequest
                          {
                              Method = HttpVerb.Get,
                              //Path = "/user/1",
                              Path = "/user",
                              Headers = new Dictionary<string, object>
                              {
                        { "Accept", "application/json" }
                              }
                          })
                          .WillRespondWith(new ProviderServiceResponse
                          {
                              Status = 200,
                              Headers = new Dictionary<string, object>
                              {
                        { "Content-Type", "application/json; charset=utf-8" }
                              },
                              Body = Match.Type("Test")
                          });`

[Pact  File.txt](https://github.com/pact-foundation/pact-provider-verifier/files/3352001/Pact.File.txt)

Error
![image](https://user-images.githubusercontent.com/44140755/60540819-bbb80800-9d2d-11e9-89be-0b431610dbfc.png)

**Comment by mefellows** [comment]
You have a matcher that says you expect `applicatinon/json` but are returning a string. That's not JSON. So your matcher needs to update to `text/plain` or your provider needs to return JSON as expected.

**Comment by tanmoy1990** [comment]
Thanks @mefellows.
I've changed the except type from `application/json` to `text/plain` but still facing the same issue. 

[Pact  File.txt](https://github.com/pact-foundation/pact-provider-verifier/files/3352946/Pact.File.txt)
![image](https://user-images.githubusercontent.com/44140755/60557526-78788c00-9d63-11e9-882c-7cf5faff0968.png)

**Comment by mefellows** [comment]
Your provider seems to be sending `Content-Type: application/json` even though you're returning a string. It shouldn't do this, because it isn't JSON.

Pact is respecting the content-type header in the response.
