### ISSUE TITLE
Failed to Compare simple string using pact

### ISSUE THREAD

**Issue by tanmoy1990** [pact-foundation/pact-provider-verifier#36]
Existing link :: https://github.com/pact-foundation/pact-provider-verifier/issues/35#issue-463397863

**Comment by tanmoy1990** [comment]
It seems like pact is always expecting that the end point should return any JSON output instead of any simple output like string

**Comment by mefellows** [comment]
If this is indeed true, please provide an example code base that demonstrates this (and ensure the correct headers are being sent by the provider:  `Content-Type: application/json`)
