### ISSUE TITLE
PUBLISH_VERIFICATION_RESULTS=false doesn't work

### ISSUE THREAD

**Issue by bogdbo** [pact-foundation/pact-provider-verifier#43]
`--publish-verification-results=PUBLISH_VERIFICATION_RESULTS`

The above flag cannot be set to false. Any value is considered true. I have tried empty string, 'null', 'nil', 'false', '0'. It's always read as true. 

Any ideas?

**Comment by mefellows** [comment]
Assuming you don't want to publish verification results, could you just not pass the flag at all?

**Comment by mefellows** [comment]
It's really intended to be a _flag_, rather than an _option_. The presence of the flag indicates a `true` value, and the absence a `false`.

**Comment by bogdbo** [comment]
I understand, I would have liked it to be configurable though. Maybe my setup is not ideal but I only want to publish the results when running builds from `master` and it's easy to set the value from true to false in my build pipelines but rather annoying to remove a whole flag from the command line. If there's no plan to change this, then feel free to close the issue.

**Comment by mefellows** [comment]
It might be possible already, but if not, I'll let @bethesque answer the question as to whether it is or will be supported.

**Comment by bethesque** [comment]
I can change it to allow the flag to be set by an environment variable, just like PACT_BROKER_USERNAME etc. `PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true`

For now, you can do:

```
publish_flag=$( [ "$PUBLISH_VERIFICATION_RESULTS" == "true" ] && echo "--publish-verification-results" )
verify --other-options ${publish_flag}
```

**Comment by bogdbo** [comment]
Thanks. I got it working as well in the meantime. I think either checking the ENV variable or updating the documentation would both be reasonable fixes.

**Comment by bethesque** [comment]
Btw, if you read the output of the `help` command you'll see this:

```
  -r, [--publish-verification-results], [--no-publish-verification-results]  # Publish verification results to the broker
```

**Comment by bethesque** [comment]
You can now set the environment variable `PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true`

**Comment by bogdbo** [comment]
Thank you  for the update @bethesque!
