### ISSUE TITLE
No output from pact-provider-verifier

### ISSUE THREAD

**Issue by moritztk** [pact-foundation/pact-provider-verifier#48]
I dont know what I am doing wrong. It's not working, but I dont get an error neither. When I run
```
pact/bin/pact-provider-verifier $PACT_URL  --provider-base-url=http://0.0.0.0:8001   --broker-token=$TOKEN   --custom-provider-header="$HEADER" 
```
just nothing happens.
![Screenshot from 2020-01-31 12-13-01](https://user-images.githubusercontent.com/36471066/73535175-3d3a5a80-4423-11ea-9829-bf2cddbc691a.png)

**Comment by mefellows** [comment]
What are the values of those variables? I was able to reproduce the "nothing response" if `$PACT_URL` was empty. Sounds like at least a better response is warranted in either case!

**Comment by moritztk** [comment]
Thanks for your answer!
It was a value, just replaced it with vars for the screenshot.
Either way, I had to move on now and will tackle this issue another day.

**Comment by moritztk** [comment]
Ok, I am already back. If it helps, I used the verifier that is shipped with pact-python. I will now double check and let you know about the url.
