### ISSUE TITLE
Multiple custom-provider-header

### ISSUE THREAD

**Issue by ChengLiPP** [pact-foundation/pact-provider-verifier#55]
Hello @bethesque,

When setting up my project I noticed that if multiple custom-provider-header are passed in the cli, later invocation will overwrite the former one. It looks like this

if I do this
`pact-verifier --provider-base-url=http://localhost:18000/ --custom-provider-header="Authorization: ABC" --custom-provider-header="x-app-name: my_app" ./my_contract.json`
The request will only contain x-app-name in the headers, if I do the reverse
`pact-verifier --provider-base-url=http://localhost:18000/ --custom-provider-header="x-app-name: my_app"  --custom-provider-header="Authorization: ABC" ./my_contract.json`
I would only get Authorization in the headers, is this something you could take a look at? Many thanks 🙏 

Pre issue-raising checklist
I have already (please mark the applicable with an x):

 Upgraded to the latest version 

Software versions
pact-python=0.21.0
OS: e.g. Mac OSX 10.14.6

Steps to reproduce
I created a tiny project to demonstrate the problem
https://github.com/ChengLiPP/pact-custom-provider-header-issue

**Comment by bethesque** [comment]
Thanks for submitting a bug with a reproducible example!

This is a problem with the python wrapper. As you can see in this [build](https://travis-ci.org/github/pact-foundation/pact-ruby-standalone-e2e-example/builds/679268635#L241) both headers are applied (commit [here](https://github.com/pact-foundation/pact-ruby-standalone-e2e-example/commit/71a985b785fa3f7a01ed5762c3fa5648c10b54b9)).

Can you please raise the issue in https://github.com/pact-foundation/pact-python

**Comment by pcwinters** [comment]
@ChengLiPP, I came across the same problem and had to look into pact's spec/test files to find that it works if you drop the equals sign when adding the CLI option

use
`--custom-provider-header "Authorization: ABC"`
instead of:
`--custom-provider-header="Authorization: ABC"`

**Comment by ChengLiPP** [comment]
@pcwinters I remember trying both and neither worked, I was using the binary `pact-verifier` that comes from pact-python instead of the original ruby implementation and Beth identified it being a problem with the python wrapper.
Elliott opened a PR to address the issue https://github.com/pact-foundation/pact-python/pull/134

**Comment by pcwinters** [comment]
@ChengLiPP I've reproduced this using the latest docker CLI image. I don't have a reproducible project to share, but basically I'm running this
```
docker run -v $PWD:/var/app -it --rm pactfoundation/pact-cli:latest verify \
    /var/app/test.pact.json \
    --provider-base-url http://docker.for.mac.host.internal:5000/myservice \
    --custom-provider-header "Foo: bar" \
    --custom-provider-header "Fizz: buzz" \
    --provider "myProvider"
```
As far as I understand, none of the above involves python. Rather, the docker image uses this project.

**Comment by ChengLiPP** [comment]
Thank you for the example. Yes starting with the python CLI was a mistake 😄 my colleage also told me he didn't run into issues with the Docker image. But I'm glad my hair-scratching picked out a small bug for the next guy that stares at this and wonders about the meaning of life.

**Comment by ChengLiPP** [comment]
@pcwinters I got it working with the docker CLI, thanks a lot 👍
