### ISSUE TITLE
Provider states should not be required

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-provider-verifier#6]
The whole provider states rigmarole is and should not be required for simpler use cases. Make this optional.

**Comment by sk1talets** [comment]
@mefellows 
hey, what would be the right place to change it? Check a configuration parameter in ProviderStateManager?

**Comment by mefellows** [comment]
Actually nothing is required - if you don't specify the `--provider_states_url` flag it will simply ignore this.

See: https://github.com/pact-foundation/pact-provider-verifier/blob/master/lib/pact/provider_verifier/pact_helper.rb#L7

**Comment by sk1talets** [comment]
@mefellows but the tests will fail because of the missing states unless the state names are empty:
```module Pact
  module Provider::State
    class ProviderStateManager
 <...>
      def set_up_provider_state
        get_global_base_provider_state.set_up
        get_consumer_base_provider_state.set_up
        if provider_state_name
          get_provider_state.set_up  <<<<<<<<<<<<<< here
        end 
      end 

<...>
```

**Comment by mefellows** [comment]
I see, so basically you are using provider states, but don't want to setup the URLs - yes?

The scenario I was envisaging originally was for tests that didn't use states.

I'll re-open this one, I believe there has been recent discussion on this in the JVM space too.

**Comment by mefellows** [comment]
I would suggest if we implement this, we should log a warning to note that states exist in the tests, but the supporting setup does not exist.

**Comment by sk1talets** [comment]
> I see, so basically you are using provider states, but don't want to setup the URLs - yes?

Right. We're trying to use different user accounts with different states instead. But would be still good to have state names as a documentation.

> I would suggest if we implement this, we should log a warning to note that states exist in the tests, but the supporting setup does not exist.

Agree.
I was hoping that it's possible to fix/workaround on the `pact-provider-verifier` side.

**Comment by mefellows** [comment]
It should be possible - I mean it _is_ Ruby, so pretty much anything is :)

From what I can tell, as long as there is the `set_up` block (https://github.com/pact-foundation/pact-provider-verifier/blob/master/lib/pact/provider_verifier/pact_helper.rb#L34-L42) we should be OK - it can just do nothing.

This should satisfy the needs of `provider_state_manager.set_up_provider_state`.

Potentially, just moving the `if ENV['provider_states_url']` into the `set_up_state` (https://github.com/pact-foundation/pact-provider-verifier/blob/master/lib/pact/provider_verifier/pact_helper.rb#L9) method might be enough - worth a shot!

**Comment by sk1talets** [comment]
But we still need consumer and provider states names, right? Should we take them from pact?

**Comment by mefellows** [comment]
Yes and yes 😀

On Dec 6, 2016 7:54 PM, "Valeriy Kassenbaev" <notifications@github.com>
wrote:

But we still need consumer and provider states names, right? Should we take
them from pact?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/pact-foundation/pact-provider-verifier/issues/6#issuecomment-265094883>,
or mute the thread

**Comment by bethesque** [comment]
This has been done now.
