### ISSUE TITLE
RegEx is matched even though it shouldn't be

### ISSUE THREAD

**Issue by cyuanli** [pact-foundation/pact-provider-verifier#75]
Hi everyone,

I'm rather new to Pact and still learning about its inner workings, so I'm not sure if I'm reporting this in the right repository. The issue I get is the following:

`MISSION_e74c7e876e9a3f29f25068929085` is matched with `^[0-9a-zA-Z-]+` even though I forgot to specify the underscore in the string. Removing the capital letters (`^[0-9a-z]+`) fails the test, as expected:

```
     Failure/Error: expect(actual_contents).to match_term expected_contents, diff_options, example
     
       Actual: {"missionId":{"id":"MISSION_e74c7e876e9a3f29f25068929085"}}
     
       Diff
       --------------------------------------
       Key: - is expected 
            + is actual 
       Matching keys and values are not shown
       
        {
          "missionId": {
       -    "id": /^[0-9a-z]+/
       +    "id": "MISSION_e74c7e876e9a3f29f25068929085"
          }
        }
```

But for `^[0-9a-zA-Z-]+` it passes.

**Comment by YOU54F** [comment]
The error from Pact is correct, your regex, doesn't care about the underscore, its gets a match for `MISSION`

![Screenshot 2023-05-11 at 20 53 19](https://github.com/pact-foundation/pact-provider-verifier/assets/19932401/44a637c2-9ed6-4e1f-bb45-517152168ce4)


You can test it on https://regex101.com/

**Comment by YOU54F** [comment]
You need to update your regex to not be so liberal
