### ISSUE TITLE
Array "min" not respected

### ISSUE THREAD

**Issue by SchulteMarkus** [pact-foundation/pact-provider-verifier#8]
Hi there,

I have used [pact-jvm-consumer-junit](https://github.com/DiUS/pact-jvm/tree/master/pact-jvm-consumer-junit) for creating a Pact from shop-checkout-service (consumer) to market-service (provider)
- [shop-checkout-service-market-service.txt](https://github.com/pact-foundation/pact-provider-verifier/files/901919/shop-checkout-service-market-service.txt)

I am using pact-provider-verifier for verification. 
The provider-verification fails, though I except it to be valid. It seems, as if 

    "$.body.markets": {"min": 1, ...},

is not respected. And because my market-service sends two markets, not exactly one, the verification fails. 
My workaround is, to add one more market to the Pact. Using this workaround, the verification works fine.

Here is the complete (failure case) output.
```
markus-tarent@markus-Aspire-VN7-592G ~ $ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
markus-tarent@markus-Aspire-VN7-592G ~ $ gem list | grep pact-provider-verifier
pact-provider-verifier (0.0.12)
markus-tarent@markus-Aspire-VN7-592G ~ $ pact-provider-verifier --provider_base_url=http://localhost:48081/ --pact_urls=shop-checkout-service-market-service.json
Reading pact at shop-checkout-service-market-service.json
WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['markets']

Verifying a pact between shop-checkout-service and market-service
  Get all markets with full information
    with GET /markets
      returns a response which
        has status code 200
        has a matching body (FAILED - 1)
        includes headers
          "Content-Type" with value /application\/json; charset=utf-8/

Failures:

  1) Verifying a pact between shop-checkout-service and market-service Get all markets with full information with GET /markets returns a response which has a matching body
     Failure/Error: expect(response_body).to match_term expected_response_body, diff_options
       Actual: {"markets":[{"Typo3Id":32,"name":"Bottrop","phone":"02041/706 071-0","sapId":"3633"},{"Typo3Id":195,"name":"Troisdorf","phone":"02241/951 80-0","sapId":"3248"}]}
       
       @@ -1,7 +1,7 @@
        {
          "markets": [
            ... ,
       -    Pact::UnexpectedIndex,
       +    Hash,
          ]
        }
       
       Key: - means "expected, but was not found". 
            + means "actual, should not be found". 
            Values where the expected matches the actual are not shown.
     # /usr/local/bin/pact-provider-verifier:23:in `<main>'

Finished in 0.03109 seconds
3 examples, 1 failure

bundle exec rake pact:verify:at[/home/markus-tarent/gospace/src/market-service/integrationtest/pacts/shop-checkout-service-market-service.json] PACT_DESCRIPTION="Get all markets with full information" PACT_PROVIDER_STATE="" # Get all markets with full information

For assistance debugging failures, run `bundle exec rake pact:verify:help`
```

This issue was discussed on [Stackoverflow](https://stackoverflow.com/questions/42948214/pact-verify-provider-what-does-pactunexpectedindex-mean)

**Comment by katloo** [comment]
I'm also having this issue using the pact provider verifier docker image. I'm pulling the latest image; but is it using v2 or is there a way to enforce it?

**Comment by mefellows** [comment]
Hi all, apologies I didn't see these!

I've recently noticed this myself and if it's not defaulting to v2, I will take it up with the Ruby maintainers.

**Comment by bethesque** [comment]
Can someone assign this to me (and add me as an admin, because I can't do it myself).

**Comment by mefellows** [comment]
Done!

**Comment by bethesque** [comment]
The pact writing code on the consumer side is missing one of the rules. Have a look at this example here: https://github.com/pact-foundation/pact-specification/blob/version-2/testcases/request/body/array%20with%20at%20least%20one%20element%20matching%20by%20example.json 
The [*].* rule is missing that says, match the *contents* of the array by type. The match: type rule on the array element only applies to the array elements itself. @uglyog, can you fix this?

**Comment by uglyog** [comment]
I have raised an issue for this, even though I don't think it is necessary. What is the point of having a type matcher on an array and then have to say that the contents must have an explicit type matcher too. 

Surely

                   "$.body.markets": {
                        "min": 1,
                        "match": "type"
                    }

means match the contents of the array by type?  Why would you match the array by type and then not the contents?

**Comment by bethesque** [comment]
Hm, good point. I feel like I must have had a reason for it though - trying to recall my logic from 3 years ago.

**Comment by bethesque** [comment]
@uglyog I think it may have something to do with wanting to allow a nested exact type matcher within the array. So you could have 

```ruby
{
  markets: Pact.each_like(name: "blah", foo: Pact.value("bar"))
}

"$.body.markets": {
                    "min": 1,
                    "match": "type"
                }
"$.body.markets[*].*": {"match" : "type"},
"$.body.markets[*].foo": {"match" : "value"}
```

Though, you could say that you just assume the [*].* rule. Having been back in the matching code again, it's actually the markets[*].* rule that indicates the intent of the matching better than the markets rule. It's the content that we're doing the type based matching on, not the array itself.

**Comment by uglyog** [comment]
That's my point, having both is redundant.

**Comment by bethesque** [comment]
I think I'm convinced. I can't remember my logic for using both. If we're going to keep one, I think it should be "$.body.markets[*].*"

**Comment by SchulteMarkus** [comment]
Any news here?

**Comment by bethesque** [comment]
I thought @uglyog had added the extra rule to the JVM impl?

**Comment by bethesque** [comment]
(We'll likely cut it down to two rules in the next version)

**Comment by uglyog** [comment]
No, @uglyog added an issue to add the extra rule to the JVM impl.

**Comment by SchulteMarkus** [comment]
ok - I asked, because I am using the latest JVM-impl. (3.5.0) and I am still having the problem.
@uglyog, can you please link to the JVM-impl. issue?

**Comment by uglyog** [comment]
https://github.com/DiUS/pact-jvm/issues/416

**Comment by adamrodger** [comment]
@bethesque @uglyog I'm having exactly the same problem using PactNet 2.0.6-beta (C# library) which uses the standalone Ruby version of Pact Verifier (v1.1.1).

I have this interaction:

```json
{
  "description": "a request for animals",
  "providerState": "some animals exist",
  "request": {
    "method": "GET",
    "path": "/api/animals",
    "headers": {
      "Accept": "application/json"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json; charset=utf-8"
    },
    "body": [
      { "name": "Dog", "sound": "Woof", "legs": 4 },
      { "name": "Kangaroo", "sound": "Errrmmmmm...?", "legs": 2 }
    ],
    "matchingRules": {
      "$.body": {
        "min": 1,
        "match": "type"
      },
      "$.body[*].*": {
        "match": "type"
      }
    }
  }
}
```

When my service returns exactly 2 animals then the pact passes. However, if my service returns more than two animals then the pact fails, but I thought the "min" rule should prevent that from happening. When I run the pact verifier though, I can see that the rule is being ignored...

```
WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']
```

From looking at this issue it appears as though this is a bug/limitation of the verifier and not a mistake in my pact file. Is that correct?

**Comment by adamrodger** [comment]
@bethesque I've found an example from the e2e tests which does exactly what I'm trying to do, so I don't really understand why mine doesn't work :smile: 

https://github.com/pact-foundation/pact-ruby-e2e-example/blob/master/consumer/spec/pacts/foo-bar.json

That has
```json
"matchingRules": {
          "$.body.company": {
            "match": "type"
          },
          "$.body.factories": {
            "min": 1
          },
          "$.body.factories[*].*": {
            "match": "type"
          }
        }
```

**Comment by bethesque** [comment]
There is an extra `  "match": "type"` in the body rules. This may be stuffing it up. It looks like you may have nested `likes` inside each other. Can you show me the code you used to create the pact? And the logs from the mock service?

**Comment by bethesque** [comment]
Ok, I've updated the ruby code to handle that extra match rule. @neilcampbell I've put out a new release of the ruby standalone. Can you update it when you have a moment?

@adamrodger if you can find where the standalone code is in the .net code on your machine, you can download the latest (1.1.2) package from the [releases](https://github.com/pact-foundation/pact-ruby-standalone/releases) page and copy it over the top. Let me know how you go.

**Comment by neilcampbell** [comment]
@bethesque @adamrodger This has been updated and released in 2.0.7-beta

**Comment by bethesque** [comment]
Closing.

**Comment by Dolly2315** [comment]
I think the issue I am facing is also because of array length  .Can you guys tell me how to write test for it .

https://stackoverflow.com/questions/53503275/pact-provider-verification-expected-an-array-but-got-a-hash
